Modified znc tunnel function

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -185,14 +185,19 @@ function extract () {
   fi
 }
 
-function znc_tunnel() {
+function znc() {
   echo "Setting up ssh tunnel..."
-  ssh -M -S .znc_tunnel -N -f znc
+  ssh -M -S ~/.ssh/znc_socket -N -f znc
+  rc=$?
+  if [[ $rc != 0 ]]; then
+    echo "Establishing connection failed"
+    exit $rc
+  fi
   echo "Waiting for tunnel to establish..."
   sleep 3
   irssi -c localhost -p 6667 
   echo "Shutting down ssh tunnel..."
-  ssh -S .znc_tunnel -O exit znc > /dev/null 2>&1
+  ssh -S ~/.ssh/znc_socket -O exit znc > /dev/null 2>&1
   echo "Done"
 }
 
